plugins:
  user_by_external_sso_enabled:
    default: true
    client: true
  user_by_external_sso_website:
    default: ''
    client: true
  user_by_external_sso_api_key:
    default: ''
    client: true
  

